### ISSUE TITLE
没太看懂 const [, setState] = useState() 这段代码的意思

### ISSUE THREAD

**Issue by CatAndDog99** [yisbug/iostore#8]
这段代码具体是什么意思

**Comment by yisbug** [comment]
等同于 const [state, setState] = useState();
如果后续代码不会用到 state 这个变量，则可以简写为 [, setState]，类似于数组。
例如数组 a = [1,2,3,4,5]，取最后一个元素，可以简写为 const [...lastItem] = a;

**Comment by CatAndDog99** [comment]
额。。 意思是如果简写的话，state就相当于用不了对吧？会报is not defined

**Comment by yisbug** [comment]
这里主要是利用 setState 来触发更新，不需要用 state，所以简写了。
